
#Portuguese stopWords
pt_stopwords = ['de', 'a', 'o', 'que', 'e', 'do', 'da', 'em', 'um', 'para', 'com',
 'n\xc3\xa3o', 'uma', 'os', 'no', 'se', 'na', 'por', 'mais', 'as', 'dos', 'como', 
'mas', 'ao', 'ele', 'das', '\xc3\xa0', 'seu', 'sua', 'ou', 'quando', 'muito', 
'nos', 'j\xc3\xa1', 'eu', 'tamb\xc3\xa9m', 's\xc3\xb3', 'pelo', 'pela', 'at\xc3\xa9',
'isso', 'ela', 'entre', 'depois', 'sem', 'mesmo', 'aos', 'seus', 'quem', 'nas', 'me', 
'esse', 'eles', 'voc\xc3\xaa', 'essa', 'num', 'nem', 'suas', 'meu', '\xc3\xa0s', 'minha',
 'numa', 'pelos', 'elas', 'qual', 'n\xc3\xb3s', 'lhe', 'deles', 'essas', 'esses', 'pelas', 
'este', 'dele', 'tu', 'te', 'voc\xc3\xaas', 'vos', 'lhes', 'meus', 'minhas', 'teu', 'tua', 
'teus', 'tuas', 'nosso', 'nossa', 'nossos', 'nossas', 'dela', 'delas', 'esta', 'estes', 
'estas', 'aquele', 'aquela', 'aqueles', 'aquelas', 'isto', 'aquilo', 'estou', 'est\xc3\xa1',
 'estamos', 'est\xc3\xa3o', 'estive', 'esteve', 'estivemos', 'estiveram', 'estava', 
'est\xc3\xa1vamos', 'estavam', 'estivera', 'estiv\xc3\xa9ramos', 'esteja', 'estejamos', 
'estejam', 'estivesse', 'estiv\xc3\xa9ssemos', 'estivessem', 'estiver', 'estivermos', 
'estiverem', 'hei', 'h\xc3\xa1', 'havemos', 'h\xc3\xa3o', 'houve', 'houvemos', 'houveram', 
'houvera', 'houv\xc3\xa9ramos', 'haja', 'hajamos', 'hajam', 'houvesse', 'houv\xc3\xa9ssemos', 
'houvessem', 'houver', 'houvermos', 'houverem', 'houverei', 'houver\xc3\xa1', 'houveremos',
 'houver\xc3\xa3o', 'houveria', 'houver\xc3\xadamos', 'houveriam', 'sou', 'somos', 's\xc3\xa3o',
 'era', '\xc3\xa9ramos', 'eram', 'fui', 'foi', 'fomos', 'foram', 'fora', 'f\xc3\xb4ramos', 
'seja', 'sejamos', 'sejam', 'fosse', 'f\xc3\xb4ssemos', 'fossem', 'for', 'formos', 'forem', 
'serei', 'ser\xc3\xa1', 'seremos', 'ser\xc3\xa3o', 'seria', 'ser\xc3\xadamos', 'seriam', 
'tenho', 'tem', 'temos', 't\xc3\xa9m', 'tinha', 't\xc3\xadnhamos', 'tinham', 'tive', 'teve', 
'tivemos', 'tiveram', 'tivera', 'tiv\xc3\xa9ramos', 'tenha', 'tenhamos', 'tenham', 'tivesse',
 'tiv\xc3\xa9ssemos', 'tivessem', 'tiver', 'tivermos', 'tiverem', 'terei', 'ter\xc3\xa1', 
'teremos', 'ter\xc3\xa3o', 'teria', 'ter\xc3\xadamos', 'teriam']


#English StopWords
english_stopwords = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 
'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 
'hers', 'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves',
 'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are', 'was',
 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 
'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at',
'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before',
 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 
'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how',
 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor',
'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just',
 'don', 'should', 'now']
